name: Android CI 2

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: ["compiler", "master"]
    paths: ["**/.github/**"]
  workflow_dispatch:
    inputs:
      withDeploy:
        type: choice
        default: no
        description: with deploy
        required: false
        options:
          - yes
          - no
  workflow_call:
     secrets:
       ACCESS_TOKEN:
         required: true
  schedule:
  # https://crontab.guru/#0_0_*/5_*_*
    - cron: '0 0 */5 * *'
jobs:
  build:
    name: build apk
    runs-on: ubuntu-latest
    env:
      # The name of the main module repository
      main_project_module: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: dimaslanjaka/dev
          ref: android-traffic
          token: ${{ secrets.ACCESS_TOKEN }}
          lfs: 'true'
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 19
          distribution: oracle
      - name: Setup cache gradle wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            $HOME/.m2/repository
            ~/.m2/repository
            ./.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
            gradle-${{ runner.os }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Generate dictionaries
        run: ./gradlew genDict --gradle-user-home .gradle -Dorg.gradle.jvmargs="-Xmx2000m -Xms300m"
      - name: build Aarch64
        run: bash ./gradlew assembleAarch64Release --gradle-user-home .gradle -Dorg.gradle.jvmargs="-Xmx2000m -Xms300m"
      - name: build ARM
        run: bash ./gradlew assembleArmRelease --gradle-user-home .gradle -Dorg.gradle.jvmargs="-Xmx2000m -Xms300m"
      - name: build X86
        run: bash ./gradlew assembleX86Release --gradle-user-home .gradle -Dorg.gradle.jvmargs="-Xmx2000m -Xms300m"
      - name: build X86_64
        run: bash ./gradlew assembleX86_64Release --gradle-user-home .gradle -Dorg.gradle.jvmargs="-Xmx2000m -Xms300m"
      - name: build manager
        run: bash ./gradlew :manager:assembleRelease --gradle-user-home .gradle -Dorg.gradle.jvmargs="-Xmx2000m -Xms300m"
      - name: aarch64
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/aarch64/release/exchanger-release.apk
          name: exchanger-android-aarch64.zip
      - name: x86_64
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/x86_64/release/exchanger-release.apk
          name: exchanger-android-x86_64.zip
      - name: x86
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/x86/release/exchanger-release.apk
          name: exchanger-android-x86.zip
      - name: arm
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/arm/release/exchanger-release.apk
          name: exchanger-android-arm.zip
      - name: manager
        uses: actions/upload-artifact@v4
        with:
          path: manager/build/outputs/apk/release/manager-release.apk
          name: manager-android.zip
