name: Android CI 2

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: ["compiler", "master"]
    paths: ["**/.github/**"]
  workflow_dispatch:
    inputs:
      withDeploy:
        type: choice
        default: no
        description: with deploy
        required: false
        options:
          - yes
          - no
  workflow_call:
     secrets:
       ACCESS_TOKEN:
         required: true

jobs:
  build:
    name: build apk
    runs-on: ubuntu-latest
    env:
      # The name of the main module repository
      main_project_module: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: dimaslanjaka/dev
          ref: android-traffic
          token: ${{ secrets.ACCESS_TOKEN }}
          lfs: 'true'
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: oracle
      - name: cache gradle wrapper folders
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            $HOME/.m2/repository
            ~/.m2/repository
            ./.gradle
          key: gradle-${{ runner.os }}
          restore-keys: gradle-${{ runner.os }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Generate dictionaries
        run: ./gradlew genDict --gradle-user-home .gradle
      - name: build Aarch64
        run: bash ./gradlew assembleAarch64Release --gradle-user-home .gradle
      - name: build ARM
        run: bash ./gradlew assembleArmRelease --gradle-user-home .gradle
      - name: build X86
        run: bash ./gradlew assembleX86Release --gradle-user-home .gradle
      - name: build X86_64
        run: bash ./gradlew assembleX86_64Release --gradle-user-home .gradle
      - name: build manager
        run: "bash ./gradlew :manager:assembleRelease --gradle-user-home .gradle"
      - name: upload apk
        uses: actions/upload-artifact@v3
        with:
          name: Exchanger apk
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
